<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPjGiTFD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPjGiTFD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPjGiTFD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPjGiTFD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPjGiTFD\App_KernelDevDebugContainer([
    'container.build_hash' => 'PjGiTFD',
    'container.build_id' => '87cfd067',
    'container.build_time' => 1633469560,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPjGiTFD');
